-- Esquema sugerido para Supabase (PostgreSQL)
-- Ejecutar en SQL Editor de Supabase si no desean que Hibernate cree la tabla automáticamente.

create table if not exists public.historico_inmubles (
    id bigint generated by default as identity primary key,
    codigo_numerico_inmueble text,
    fecha_creacion timestamptz,
    cliente_asociado bigint,
    estado_codigo text
);

create index if not exists idx_historico_inmubles_cliente_asociado
    on public.historico_inmubles (cliente_asociado);

create index if not exists idx_historico_inmubles_estado_codigo
    on public.historico_inmubles (estado_codigo);
