# ==============================================================
# 1. CONFIGURACIÓN DEL SERVIDOR
# ==============================================================
# Nombre de la aplicación (útil para logs y monitoreo)
spring.application.name=middleware-service-habitar-inmobiliaria
spring.config.import=optional:file:.env[.properties]


# Puerto donde correrá el backend (8080 es el default, pero es bueno explicitarlo)
server.port=8080

# ==============================================================
# 2. INTEGRACIÓN CON WASI (INVENTARIO)
# ==============================================================
# URL base de la API de Wasi
wasi.api.url=https://api.wasi.co/v1

# ¡OJO! Aquí usamos la sintaxis ${NOMBRE_VARIABLE}
# Spring buscará una variable de entorno llamada WASI_ID_COMPANY
# Si no la encuentra, fallará al iniciar (esto es bueno, evita arrancar sin credenciales)
wasi.id.company=${WASI_ID_COMPANY}
wasi.token=${WASI_TOKEN}

# ==============================================================
# 3. INTEGRACIÓN CON HUBSPOT (CRM)
# ==============================================================
# Token de la Private App (Debe comenzar con pat-na1-...)
hubspot.token=${HUBSPOT_TOKEN}

# ==============================================================
# 4. CONFIGURACIÓN DE SWAGGER / OPENAPI
# ==============================================================
# Ruta para acceder a la documentación visual
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta para obtener el JSON de la especificación
springdoc.api-docs.path=/v3/api-docs
# Ordenar los endpoints alfabéticamente en la UI
springdoc.swagger-ui.operations-sorter=method

# ==============================================================
# 5. LOGS Y DEBUGGING (Nivel Mentor)
# ==============================================================
# Nivel general de logs: INFO (Solo lo importante)
logging.level.root=INFO
# Nivel para NUESTRO código: DEBUG (Para ver todo lo que pasa en nuestros paquetes)
logging.level.com.habitar.middleware=DEBUG

# Nivel para ver las peticiones HTTP de Feign (¡Vital para debugging!)
# Esto nos mostrará en consola: [WasiClient] ---> GET https://api.wasi.co...
logging.level.com.habitar.middleware.client=DEBUG

# ==============================================================
# 6. TIMEOUTS (RESILIENCIA)
# ==============================================================
# Si Wasi tarda más de 5 segundos en responder, cortamos la conexión.
# Esto evita que el middleware se quede "colgado" esperando eternamente.
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Activar OkHttp para soportar PATCH
spring.cloud.openfeign.okhttp.enabled=true

